CREATE TABLE IF NOT EXISTS reparaciones (
    id                     INT AUTO_INCREMENT PRIMARY KEY,
    cuenta_id              INT NOT NULL,
    veterinaria_id         INT NOT NULL,
    cliente_id             INT NULL,
    cliente_nombre         VARCHAR(150) NOT NULL,
    cliente_telefono       VARCHAR(30) DEFAULT '',
    tipo_equipo            VARCHAR(60) DEFAULT '',
    marca                  VARCHAR(60) NOT NULL,
    modelo                 VARCHAR(150) NOT NULL,
    color                  VARCHAR(40) DEFAULT '',
    serial                 VARCHAR(100) DEFAULT '',
    clave_equipo           VARCHAR(100) DEFAULT '',
    falla                  VARCHAR(255) NOT NULL,
    observaciones          TEXT NULL,
    accesorios             VARCHAR(255) DEFAULT '',
    costo_total            DECIMAL(10,2) NOT NULL DEFAULT 0,
    abono                  DECIMAL(10,2) NOT NULL DEFAULT 0,
    descuento              DECIMAL(10,2) NOT NULL DEFAULT 0,
    referencia_pago        VARCHAR(100) DEFAULT '',
    fecha_entrega_estimada DATE NULL,
    dias_garantia          INT NOT NULL DEFAULT 30,
    estado                 ENUM('pendiente', 'en_reparacion', 'listo', 'entregado') NOT NULL DEFAULT 'pendiente',
    usuario_id             INT NOT NULL,
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_cuenta (cuenta_id),
    INDEX idx_veterinaria (veterinaria_id),
    INDEX idx_cliente (cliente_id)
);
